name: check

on:
  pull_request:
    branches: [master]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '18'

  windows:
    runs-on: windows-latest
    steps:
    - name: depends
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-libconfig
          mingw-w64-x86_64-spdlog
          mingw-w64-x86_64-uriparser
          mingw-w64-x86_64-poco
          mingw-w64-x86_64-qt6-base
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      shell: msys2 {0}
      run: cmake -B .Release -DCMAKE_BUILD_TYPE=Release && cmake --build .Release
    - name: collect
      shell: msys2 {0}
      run: |
        ./winqtcollect.sh .Release/cake.exe artifacts
        cp logo.ico artifacts
        cp .Release/_deps/candy-build/src/tun/wintun/bin/amd64/wintun.dll artifacts
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cake-portable
        path: artifacts
    - name: installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
      with:
        path: setup.iss
    - name: upload installer
      uses: actions/upload-artifact@v4
      with:
        name: cake-installer
        path: installer

