name: check

on:
  pull_request:
    branches: [master]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '18'

  windows:
    runs-on: windows-latest
    steps:
    - name: depends
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-libconfig
          mingw-w64-x86_64-spdlog
          mingw-w64-x86_64-uriparser
          mingw-w64-x86_64-poco
          mingw-w64-x86_64-qt6-base
    - name: checkout
      uses: actions/checkout@v4
    - name: cache
      uses: actions/cache@v4
      with:
        path: .Release
        key: ${{ hashFiles('CMakeLists.txt') }}
    - name: build
      shell: msys2 {0}
      run: |
        cmake -B .Release -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=".Release" -DCMAKE_INSTALL_BINDIR="artifacts"
        cmake --build .Release
        cmake --install .Release
    - name: collect
      shell: msys2 {0}
      run: |
        ./winqtcollect.sh .Release/artifacts/cake.exe .Release/artifacts
        cp logo.ico .Release
        cp .Release/_deps/candy-build/src/tun/wintun/bin/amd64/wintun.dll .Release/artifacts
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cake-portable
        path: .Release/artifacts
    - name: installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
      with:
        path: .Release/setup.iss
    - name: upload installer
      uses: actions/upload-artifact@v4
      with:
        name: cake-installer
        path: .Release/installer
